application-description: '@project.description@'
application-version: '@project.version@'
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        display-request-duration: true
        doc-expansion: none
        operations-sorter: alpha
        path: /swagger-ui.html
